services:
  web: # servizio che contiene l'app morra-flask
    build: 
      context: . # cartella contenente il Dockerfile
      network: host
    network_mode: host
    env_file: # file contenente le variabili d'ambiente
      testing_vars.env
    restart: unless-stopped
    ports:
      - 5001:5001
    entrypoint: [ "./wait-for", "postgres:5432", "--", "python", "-u", "index.py" ]
    depends_on:
      - postgres
  postgres: # servizio che contiene il database postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD:?err}
      - POSTGRES_USER = ${POSTGRES_USER:?err}
      - POSTGRES_DB = ${POSTGRES_DB:?err}
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
  