services:
  web: # servizio che contiene l'app morra-flask
    build: . # cartella contenente il Dockerfile
    env_file: # file contenente le variabili d'ambiente
      testing_vars.env
    network_mode: host
    ports:
      - 5001:5001
    entrypoint: [ "./wait-for", "postgres:5432", "--", "python", "-u", "index.py" ]
    depends_on:
      - postgres
  postgres: # servizio che contiene il database postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
  