services:
  web: # servizio che contiene l'app morra-flask
    image: grimos10/iot_backend:arm
    env_file: # file contenente le variabili d'ambiente
      testing_vars.env
    ports:
      - 5001:5001
    entrypoint: [ "./wait-for", "mysql:3307", "--", "python", "index.py" ]
  mysql:
    image: "mysql:5.7"
    platform: linux/x86_64
    restart: always
    ports:
      - "3307:3307"
    env_file:
      testing_vars.env
    volumes: # utilizzo di un volume per preservare i dati del DB
      - dbvol:/var/lib/mysql

volumes: # elenco dei volumi da creare (in questo caso uno solo)
  dbvol:
  