"""admin and finished

Revision ID: 4ba17b75bcc1
Revises: c57964072fc0
Create Date: 2025-01-29 15:56:01.423958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba17b75bcc1'
down_revision = 'c57964072fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ParkingSession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished', sa.Boolean(), nullable=True))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('admin')

    with op.batch_alter_table('ParkingSession', schema=None) as batch_op:
        batch_op.drop_column('finished')

    # ### end Alembic commands ###