"""empty message

Revision ID: c57964072fc0
Revises: 
Create Date: 2024-11-29 12:43:53.148226


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57964072fc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('User', schema=None) as batch_op:
     #   batch_op.add_column(sa.Column('car_plate', sa.String(length=10), nullable=True))
      #  batch_op.create_unique_constraint(None, ['car_plate'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('car_plate')

    # ### end Alembic commands ###
"""